# Path to Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Disable OMZ theme — oh-my-posh owns the prompt
ZSH_THEME="fino-time" # set by `omz`

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# History
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# # oh-my-posh prompt
# eval "$(~/.local/bin/oh-my-posh init zsh --config cloud-native-azure)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
