# Path to Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Disable OMZ theme — oh-my-posh owns the prompt
ZSH_THEME=""

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# History
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# # oh-my-posh prompt
# eval "$(~/.local/bin/oh-my-posh init zsh --config cloud-native-azure)"
